spring:
  redis:
    cluster:
      nodes: redis01:7000,redis02:7000,redis03:7000
    password: lKcD#t5gbZdY&MzD
    timeout: 60000ms
    jedis:
      pool:
        max-active: 1000
        max-wait: 1000ms
        max-idle: 1000
        min-idle: 100
    max-total: 1001
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    num-tests-per-eviction-run: 1000
    time-between-eviction-runs-millis: 60000
    block-when-exhausted: false